### ISSUE TITLE
testcontainers wait indefinitely without effects when running in Gitlab-CI

### ISSUE THREAD

**Issue by victornoel** [testcontainers/testcontainers-python#43] opened 2019-11-28 13:25 UTC
I'm running a test based on testcontainers-python in a container running in Gitlab CI.

Basically the CI spawns a docker-in-docker container next to the container running the tests. I then set the environment variable DOCKER_HOST so that it can be used by testcontainers.

But in practice the test just get stuck, so I ran it with `pytest -s` to see the logs of testcontainers and got:
```
tests/test.py
Pulling image postgres:10
Container started:  4a1115dc98
Waiting to be ready...
```

And then it gets stuck indefinitely (I waited 20 minutes).

For the record, testcontainers-java works perfectly with this same situation, so it should be possible to make this work.

I'm not sure how I can get more debug information to understand what is happening, but shouldn't it timeout normally at least?

**Comment by victornoel** [comment] 2019-11-28 13:29
See also #25 for a different but maybe related problem and https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/ for the how to use testcontainers-java in gitlab-ci

**Comment by GregHilston** [comment] 2020-01-09 22:50
I currently get a timeout

```
Pulling image mysql:5.7.28
⠏
Container started:  0c46b2b744
Waiting to be ready...
```

I'm using the `mysql` container and the exact log output is:

```
======================================================================= ERRORS =======================================================================
_________________________________________________________ ERROR at setup of test_with_mysql __________________________________________________________

    @pytest.fixture(scope="session")
    def mysql():
>       mysql = MySqlContainer("mysql:5.7.28").start()

tests/service/test_functional.py:9:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.7/site-packages/testcontainers/core/generic.py:49: in start
    self._connect()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

wrapped = <bound method DbContainer._connect of <testcontainers.mysql.MySqlContainer object at 0x112823110>>
instance = <testcontainers.mysql.MySqlContainer object at 0x112823110>, args = (), kwargs = {}

    @wrapt.decorator
    def wrapper(wrapped, instance, args, kwargs):
        exception = None
        print(crayons.yellow("Waiting to be ready..."))
        with blindspin.spinner():
            for _ in range(0, config.MAX_TRIES):
                try:
                    return wrapped(*args, **kwargs)
                except Exception as e:
                    sleep(config.SLEEP_TIME)
                    exception = e
            raise TimeoutException(
                """Wait time exceeded {0} sec.
                    Method {1}, args {2} , kwargs {3}.
                     Exception {4}""".format(config.MAX_TRIES,
                                             wrapped.__name__,
>                                            args, kwargs, exception))
E           testcontainers.core.exceptions.TimeoutException: Wait time exceeded 120 sec.
E                               Method _connect, args () , kwargs {}.
E                                Exception No module named 'pymysql'

venv/lib/python3.7/site-packages/testcontainers/core/waiting_utils.py:50: TimeoutException
```

I can see the container running when I check with `$ docker ps`. Also, I can make a new issue if that's helpful

**Comment by GregHilston** [comment] 2020-01-09 22:53
Turns out I can't read and apologize for posting in the first place. 

`$ pip3 install pymysql` fixed everything ha

**Comment by ismailsimsek** [comment] 2020-02-10 14:59
having same issue with gitlab cicd 


```
 $ python test.py
Pulling image mysql:5.7.17
Container started:  f2ea27afde
Waiting to be ready...
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    config = MySqlContainer('mysql:5.7.17').start()
  File "/root/.local/lib/python3.6/site-packages/testcontainers/core/generic.py", line 49, in start
    self._connect()
  File "/root/.local/lib/python3.6/site-packages/wrapt/wrappers.py", line 603, in __call__
    args, kwargs)
  File "/root/.local/lib/python3.6/site-packages/testcontainers/core/waiting_utils.py", line 50, in wrapper
    args, kwargs, exception))
testcontainers.core.exceptions.TimeoutException: Wait time exceeded 120 sec.
                    Method _connect, args () , kwargs {}.
                     Exception (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '172.18.0.2' (timed out)")
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by ismailsimsek** [comment] 2020-02-21 09:57
im using _docker:dind_ with gitlab cicd pipeline. 
adding wait for mysql to boot and changing mysql host-name to '_docker_'  solved my problem



```
from testcontainers.compose import DockerCompose
from testcontainers.core.utils import inside_container
from testcontainers.core.waiting_utils import wait_container_is_ready

class MyDockerCompose():

    def __init__(self):
        self.compose: DockerCompose = DockerCompose(self.dir_root.as_posix())
        self.compose.start()
        self.wait_for()

    @wait_container_is_ready()
    def wait_for(self):
        # wait for docker mysql to accept connections
        os.environ['TC_POOLING_INTERVAL'] = '6'
        str_stdout = Utils.run_command(command="mysql --user=%s --password=%s --host=%s --execute 'SHOW DATABASES;'" % ('test', 'test', 'test'))
        return 'MyDatabaseName' in str_stdout

```

**Comment by tillahoffmann** [comment] 2020-04-28 09:08
Fixed in #85. Feel free to reopen if problems persist.

**Closed by tillahoffmann** 2020-04-28 09:08 UTC

**Comment by victornoel** [comment] 2020-04-28 16:06
Excellent, I can confirm this works :)

**Comment by karmux** [comment] 2020-05-21 22:05
Version 3.0 gets stuck for me at the same place but 2.6 works fine when using docker-in-docker with mounted socket.

**Comment by tuvshuud** [comment] 2020-05-23 04:09
@karmux I will double check. Meanwhile, can you provide your .gitlab-ci.yml here?

**Comment by karmux** [comment] 2020-05-28 17:59
@tuvshuud it's not Gitlab-CI but Docker images based on official Python images where this freezing happens (using `-v /var/run/docker.sock:/var/run/docker.sock` argument to `docker run`). Didn't create a new bug as it seemed related.

**Comment by tillahoffmann** [comment] 2020-05-29 10:20
@karmux, could you post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please so we can have a look?

**Comment by karmux** [comment] 2020-05-29 15:51
@tillahoffmann 

Dockerfile:
```
FROM python:3.8-alpine
WORKDIR /app
RUN apk add --no-cache \
    gcc \
    git \
    libpq \
    make \
    musl-dev \
    postgresql-dev \
    && pip install --no-cache-dir \
    git+https://github.com/tuvshuud/testcontainers-python.git \
    && apk del \
    gcc \
    git \
    make \
    musl-dev \
    postgresql-dev
COPY . ./

```

Python test:
```
from testcontainers.postgres import PostgresContainer

postgres_container = PostgresContainer()
postgres = postgres_container.start()
# Gets stuck here
CONN_URL = postgres.get_connection_url()
```
Docker build:
```
docker build -t localhost/python:3.8 .
```

Docker run:
```
docker run \
    -it \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    localhost/python:3.8 \
    python -m unittest discover testing/tests/integration/
```

@tuvshuud , sorry PR #96 didn't fix it.

If I install `testcontainers[postgresql]==2.6` then it works.

**Comment by tuvshuud** [comment] 2020-06-02 08:07
As @tillahoffmann mentioned [here](https://github.com/testcontainers/testcontainers-python/issues/45#issuecomment-569508631), you have to install required additional dependencies explicitly.

So your `Dockerfile` should have `SQLAlchemy`, `psycopg2` packages installed.
```
FROM python:3.8-alpine
WORKDIR /app
RUN apk add --no-cache \
    gcc \
    git \
    libpq \
    make \
    musl-dev \
    postgresql-dev \
    && pip install --no-cache-dir \
    git+https://github.com/tuvshuud/testcontainers-python.git \
    SQLAlchemy \
    psycopg2 \
    && apk del \
    gcc \
    git \
    make \
    musl-dev \
    postgresql-dev
COPY . ./
```

I've checked and #96 fixed it. @karmux

@tillahoffmann Do you think we need more verbosity in [_connect()](https://github.com/testcontainers/testcontainers-python/blob/87fb2c14207898fa63cb77a2a2c2beadb7e5357c/testcontainers/core/generic.py#L26) , so that others can troubleshoot easily? Because of missing packages, wrong container ip address or port that is being used, testcontainer process may hang until timeout.

**Comment by tillahoffmann** [comment] 2020-06-03 14:26
There may be an opportunity to update the exceptions we catch in `wait_container_is_ready` to only include `TimeoutError`s, for example. In other words, any exception that is not a `TimeoutError`, such as an `ImportError`, would just be raised as normal. Although we'd have to make sure we don't break anything by accident.

https://github.com/testcontainers/testcontainers-python/blob/87fb2c14207898fa63cb77a2a2c2beadb7e5357c/testcontainers/core/waiting_utils.py#L40-L45

**Comment by tuvshuud** [comment] 2020-06-04 04:10
Looking at the reference of `wait_container_is_ready`, it is decorated in various areas `requests`, `webdriver` and `sqlalchemy`. So we need to handle family of `TimeoutError` such as `requests.ConnectTimeout`, `sqlalchemy.exc.TimeoutError`. Again, there might some edge cases that we may break.

Maybe we should log the exception [here](https://github.com/testcontainers/testcontainers-python/blob/87fb2c14207898fa63cb77a2a2c2beadb7e5357c/testcontainers/core/waiting_utils.py#L45) at debug level on each polling. Otherwise, one can shorten `TC_MAX_RETRIES` and get the exception output from `TimeoutException`

**Comment by karmux** [comment] 2020-06-04 21:14
Still waiting till it gets timeout with 3.0.2.

```
Pulling image postgres:latest
⠏
Container started:  2010c8ddfd
Waiting to be ready...
⠏E
======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/app/tests/test.py", line 13, in <module>
    postgres = postgres_container.start()
  File "/usr/local/lib/python3.8/site-packages/testcontainers/core/generic.py", line 42, in start
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/testcontainers/core/waiting_utils.py", line 46, in wrapper
    raise TimeoutException(
testcontainers.core.exceptions.TimeoutException: Wait time exceeded 120 sec.
                    Method _connect, args () , kwargs {}.
                     Exception (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 32788?
could not connect to server: Address not available
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 32788?

(Background on this error at: http://sqlalche.me/e/e3q8)


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

```
$ docker run -it --rm localhost/python:3.8 pip freeze
asgiref==3.2.7
blindspin==2.0.1
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
coverage==5.1
crayons==0.3.0
deprecation==2.1.0
docker==4.2.1
flake8==3.8.2
idna==2.9
mccabe==0.6.1
mypy==0.780
mypy-extensions==0.4.3
packaging==20.4
psycopg2-binary==2.8.5
pycodestyle==2.6.0
pyflakes==2.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
requests==2.23.0
six==1.15.0
SQLAlchemy==1.3.17
sqlalchemy-stubs==0.3
testcontainers==3.0.2
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
websocket-client==0.57.0
wrapt==1.12.1
```

**Comment by tuvshuud** [comment] 2020-06-05 14:11
@karmux #96 merged into master but hasn’t released into patch version yet. Meanwhile you may try with `pip install git+https://github.com/testcontainers/testcontainers-python.git`

**Comment by karmux** [comment] 2020-06-05 20:49
Works now! Thank you @tuvshuud and @tillahoffmann!

**Comment by tillahoffmann** [comment] 2020-06-08 17:05
`3.0.3` is now on pypi so you should be able to revert to `pip install testcontainers` without the need to install from `master`. Thanks for the fix, @tuvshuud.

**Comment by ypatel26** [comment] 2020-06-08 18:06
Mine is still hanging.  I updated testcontainer to 3.0.3 from above link.  Not sure what am i doing wrong.

**Comment by aashish-agarwal-de** [comment] 2021-06-05 09:06
I am running a MySQL test container inside a docker, and by default it tries to connect to the docker_host_ip, which is throwing the error.
If it connects to host.docker.internal then it works, but the package does not allow that

**Comment by aashish-agarwal-de** [comment] 2021-06-05 09:16
In my case I am running MySQL Test container within docker, and when I do MysqlContainer.start(), it tries by default to connect to docker_host ip, which is causing the issue.
Do I have to add some flag in docker run command?

**Comment by tuvshuud** [comment] 2021-06-05 09:39
@aashish-agarwal-de you can use TC_HOST environment variable to set correct host address if host detection in the library is not working correctly.

**Comment by aashish-agarwal-de** [comment] 2021-06-05 09:40
It is detecting the gateway host, byt sql alchemy is not able to connect to that ip.
It is only able to connec to host.docker.internal

**Comment by aashish-agarwal-de** [comment] 2021-06-05 10:32
Is there a way to pass the hostname to MySQL test container, so that it does try to connect to gatwway ip in docker?

**Comment by aashish-agarwal-de** [comment] 2021-06-05 15:45
In CI this was resolved my passing --network=host in docker run command, but I am still facing issues with running it in my local system. I am working on mac
