### ISSUE TITLE
Offer help to maintain the repo

### ISSUE THREAD

**Issue by KerstenBreuer** [testcontainers/testcontainers-python#163] opened 2021-12-10 16:46 UTC
Hi @SergeyPirogov,
 
I am working as a developer at the German Cancer Research Center (DKFZ) in Heidelberg and I absolutely love your testcontainers-python package. I am using it all the time at work and it makes my life way easier.
 
I noticed that the PRs in the repo are starting to pile up and that tests are failing. I completely understand that maintaining an open source poject that popular can be very challenging and I was wondering if you would need any help on maintaining it? I would be happy to volunteer and perform review, look at issues, etc..
 
If you like please contact me at any time via k.breuer@dkfz-heidelberg.de (or just comment here as you wish).
 
Looking forward to hearing back from you.
 
Thanks a lot and best wishes,
Kersten
 
(P.S. I have a PR open to add RabbitMQ - #168. Would be great if you could approve the workflow execution and have a look.)

**Comment by cal97g** [comment] 2021-12-10 23:43
I think bringing in additional maintainers for this project would be a good step. I think it's a good project, it's definitely very useful for integration testing and is really the only option to write pythonic integration tests that I know of. I think adding to the team of maintainers would enhance the popularity of the project, which seems to be lacking the user base of the other language implementations.

**Comment by tillahoffmann** [comment] 2021-12-11 16:39
Hey, yes, expanding the set of people who can contribute directly and maintain the code base is a good idea. I'm happy to add @KerstenBreuer unless you have objections @SergeyPirogov.

**Comment by SergeyPirogov** [comment] 2021-12-11 17:20
I dont see many requests for changes

**Comment by tillahoffmann** [comment] 2021-12-13 03:04
I think there's a bit of stuff we could do in terms of maintenance (I've closed a few outstanding issues that were resolved/didn't have a response). Maybe this thread is an opportunity to prioritise.

## Maintenance and bugs

- #161 raises issues with google cloud pubsub (presumably because the python client version used in our repo hasn't been bumped in a while).
- #159, #157, #141, #143, #138, #108, #99 roughly fall into the category of ip and/or port resolution for different host systems and/or docker in docker (some of these could probably be classed as feature requests).
- #105 is a documentation issue (possibly also a bug but the issue isn't particularly clear); possible fix in #153.
- #101 reports connections timing out, possibly a duplicate of #108 and/or #99.
- #44 looks like a bug but I haven't dug into it.

## Feature requests

- #144 to support `wait_for_logs` for docker compose (rather than just vanilla containers) with a proposed solution in #149
- #140 for extension of `get_connection_url` api.
- #126 (TimeScaleDb) and #104 (Ryuk) are requests for new container classes.
- #86 is looking for a wait strategy that checks by calling an HTTP endpoint in the container until it returns an ok status code.

## PRs

- #160, #153 are small PRs that are not going to have a material impact but we could just merge.
- #51, #162, and #142 are all trying to add RabbitMQ. Other container proposals include #152 (Trino), #148 (Minio), #139 (Kafka).
- #154 and #158 try to address some of the ip and/or port issues.

I'm sure I've missed something, but maybe we can use this list as a starting point for next steps. Something we may want to think about longer-term is to allow different people to contribute their own containers without us having to be familiar with all the different databases as maintainers (maybe using `CODEOWNERS`, maybe using a template for others to publish their own packages (similar to what `pytest` has done with `pytest-cov`, `pytest-mock`, etc.)).

**Comment by KerstenBreuer** [comment] 2021-12-13 09:49
@cal97g, @tillahoffmann thanks a lot for the feedback and @tillahoffmann thanks for giving the summary.

@SergeyPirogov, I hope my message was not misunderstood. I don't think that this repo is badly maintained. On the contrary, I see a lot of value in it and it could become a major component of our long-term software strategy. This is why, I would be happy to see this repo in the best possible shape with a high rate of community PRs being merged. If there is something I can help on, please let me know.

Either way, keep up the great work.

**Comment by KerstenBreuer** [comment] 2021-12-14 08:06
@SergeyPirogov do you have any feedback or comment? Otherwise, I think this issue can be closed.

**Comment by yakimka** [comment] 2022-01-12 12:46
@tillahoffmann @SergeyPirogov is this repository maintained? There are a lot of PR requests that no one answers for weeks or months. Are you sure you don't need help maintaining this repository?

**Comment by KerstenBreuer** [comment] 2022-01-20 16:56
Hi @SergeyPirogov, @tillahoffmann, 
I would really like this repo to be in the best possible shape. What it does is awesome and you are definitely very good maintainers.

However, since this project is becoming more and more popular it is only natural that it cannot be maintained by only two developers. 

It seems that there are lots of volunteers for maintenance (@thedrow & @naomielst - see https://github.com/testcontainers/testcontainers-python/issues/177,  @yakimka(?), and myself). I think it would be a great opportunity to make use of them.

It would be great if we can get some feedback from you.

**Comment by yakimka** [comment] 2022-01-24 19:39
@SergeyPirogov, @tillahoffmann ?

**Comment by SergeyPirogov** [comment] 2022-01-24 20:08
I will add anybody as a maintainer. Just leave your ids

**Comment by KerstenBreuer** [comment] 2022-01-25 12:44
Great thanks so much for your trust. Here would be my id: @KerstenBreuer

**Comment by thedrow** [comment] 2022-01-25 17:51
@SergeyPirogov me and @naomielst

**Comment by yakimka** [comment] 2022-01-28 21:28
@SergeyPirogov?

**Comment by KerstenBreuer** [comment] 2022-03-22 12:38
I have not received maintenance rights, yet. @thedrow, @naomielst what about you?

**Comment by thedrow** [comment] 2022-03-22 17:35
Not yet.

**Comment by yakimka** [comment] 2022-03-26 22:24
@tillahoffmann add please @KerstenBreuer as a maintainer

**Comment by Mohsin-Ul-Islam** [comment] 2022-04-08 06:22
@SergeyPirogov add me as a maintainer as well! Thanks.

**Comment by SergeyPirogov** [comment] 2022-04-08 09:03
@KerstenBreuer @thedrow you should have access

**Comment by KerstenBreuer** [comment] 2022-04-11 16:47
Sorry, I didn't receive anything. Maybe, I was also too slow and the invite already expired?

**Comment by tillahoffmann** [comment] 2022-05-04 15:01
I think everyone who's offered to contribute now has an invite. But let me know if that's not the case. @KerstenBreuer, I resent your invite.

**Closed by tillahoffmann** 2022-05-04 15:01 UTC
