### ISSUE TITLE
Cannot import name 'MySqlContainer' from 'testcontainers'

### ISSUE THREAD

**Issue by curiousjazz77** [testcontainers/testcontainers-python#45] opened 2019-12-09 02:43 UTC
I recently installed this library and also installed a few downstream dependencies that other users mentioned in old issues. I am running python 3.7. 

I have the following file:

```import pytest
import sqlalchemy
from testcontainers import MySqlContainer


@pytest.fixture(scope="session")
def mysql():
    mysql = MySqlContainer('mysql:5.7.17').start()
    engine = sqlalchemy.create_engine(mysql.get_connection_url())
    yield engine
    mysql.stop()


def test_with_mysql(mysql):
    result = mysql.execute("select version()")
    for row in result:
        assert row[0] == '5.7.17'
```

When I attempt to run `pytest test_mysql.py`, I get:
```
============================= test session starts ==============================
collected 0 items / 1 errors

==================================== ERRORS ====================================
________________________ ERROR collecting test_mysql.py ________________________
ImportError while importing test module '../test_mysql.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_mysql.py:4: in <module>
    from testcontainers import MySqlContainer
E   ImportError: cannot import name 'MySqlContainer' from 'testcontainers' 
```

Same with `python3 test_mysql`, I get:

```
ImportError: cannot import name 'MySqlContainer' from 'testcontainers' (/Users/<redacted>/Library/Python/3.7/lib/python/site-packages/testcontainers/__init__.py)
```

**Comment by tillahoffmann** [comment] 2019-12-15 12:59
Hi @curiousjazz77, can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by curiousjazz77** [comment] 2019-12-29 06:08
^ updated!

**Comment by tillahoffmann** [comment] 2019-12-29 14:05
Thanks for the example! By default, the `testcontainers` package does not import all submodules because they may require additional dependencies. For example, the `testcontainers.mysql` submodule depends on `sqlalchemy` which is not installed by default.

You should be able to fix your code by running `from testcontainers.mysql import MySqlContainer` instead. Make sure to install the package using `pip install testcontainers[mysql]` to install the required dependencies. You may need to use `pip install "testcontainers[mysql]"` depending on your shell.

I'll close this issue for now, but feel free to reopen it if you continue to have difficulties.

**Closed by tillahoffmann** 2019-12-29 14:05 UTC
