### ISSUE TITLE
docker.errors.APIError: 500 Server Error: bind: address already in use

### ISSUE THREAD

**Issue by KarinElimelech** [testcontainers/testcontainers-python#90] opened 2020-05-06 12:46 UTC
Hi! I'm using testcontainers (version 2.5) and when I load several containers from different modules the next exception appeared occasionally:

> e = HTTPError('500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/92bb224c98058c18df93f94514bf353ac4a7548fac0f40dfb74cada80050f936/start',)
> def create_api_error_from_http_exception(e):
> """
> Create a suitable APIError from requests.exceptions.HTTPError.
> """
> response = e.response
> try:
> explanation = response.json()['message']
> except ValueError:
> explanation = (response.content or '').strip()
> cls = APIError
> if response.status_code == 404:
> if explanation and ('No such image' in str(explanation) or
> 'not found: does not exist or no pull access'
> in str(explanation) or
> 'repository does not exist' in str(explanation)):
> cls = ImageNotFound
> else:
> cls = NotFound
> raise cls(e, response=response, explanation=explanation)
> E docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint dazzling_saha (de58082fa7fb5b1e69d05f7c692aa14368047e49a86673e5e7736fabf78e1c00): Error starting userland proxy: listen tcp 0.0.0.0:34927: bind: address already in use")

each time, several tests are trying to connect the same 4 ports (different ports from run to run).
I checked and the containers are closing correctly at the end of the test.

**Comment by KarinElimelech** [comment] 2020-05-06 13:58
Hi @tillahoffmann thanks for the quick response
here is the fixture:
pytest.fixture(scope="module", autouse=True)
def postgres_container():
with _postgres_container_setup():
yield

@pytest.fixture()
def postgres(request):
if 'postgres_container' not in request.funcargnames:
log.warning('')
with _postgres_container_setup() as container:
yield container
else:
postgres_testing_utils.drop_create_all_if_possible()
yield _container

@contextmanager
def _postgres_container_setup():
from testcontainers.postgres import PostgresContainer
with PostgresContainer('postgres:%s' % POSTGRES_VERSION) as container:
yield container
log.info("Postgres:%s image stopped", POSTGRES_VERSION)

and a test example that uses the fixture:
import postgres_container
def test(postgres):
...

**Comment by tillahoffmann** [comment] 2020-05-06 16:43
Hi @KarinElimelech, could you post the code again and surround it with ` ``` ` before and after? That should preserve the indentation so I can run it.

**Comment by KarinElimelech** [comment] 2020-05-07 09:50
@tillahoffmann edited

**Comment by tillahoffmann** [comment] 2020-05-07 14:23
I couldn't reproduce the issue because some of the methods were undefined, such as `postgres_testing_utils.drop_create_all_if_possible`. Having said that, the use of testcontainers in the code snippet is unconventional. See [here](https://testcontainers-python.readthedocs.io/en/latest/database.html) for some examples.

More specifically, the following should be able to address your use case. I would generally recommend against `autouse=True` because it can lead to less explicit and understandable code.

```python
# Run $ pytest -sv [filename].py to execute the tests

import pytest
from testcontainers.postgres import PostgresContainer


@pytest.fixture(scope="module")
def postgres_container():
    print('Creating container...')
    with PostgresContainer('postgres:latest') as container:
        print('Started container.')
        yield container
        print('Stopped container.')


def test_a(postgres_container):
    print('Running test A with url %s...' % postgres_container.get_connection_url())


def test_b(postgres_container):
    print('Running test B with url %s...' % postgres_container.get_connection_url())
```

I'll close this one for now, but feel free to reopen if the above doesn't address your use case.

**Closed by tillahoffmann** 2020-05-07 14:23 UTC
Labels: awaiting response
