### ISSUE TITLE
Do not always stop container on __del__

### ISSUE THREAD

**Issue by andredasilvapinto** [testcontainers/testcontainers-python#146] opened 2021-06-10 09:00 UTC
A user of the library might, for examle, not keep the reference to `DockerContainer` but use get_wrapped_container to access the underlying `Container` object and keep that instead. Currently this will produce an unexpected container stop triggered by GC.

If you want to keep this behaviour it should at least be optional (configured by a constructor `stop_on_deletion` flag for example).

Relevant code: https://github.com/testcontainers/testcontainers-python/blob/master/testcontainers/core/container.py#L69-L77

**Comment by tillahoffmann** [comment] 2021-12-13 02:39
Duplicate of #109. Let's discuss further there if needed.

**Closed by tillahoffmann** 2021-12-13 02:39 UTC
Labels: duplicate
